# Generated by Django 3.2 on 2021-04-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=50, verbose_name='Название продукта')),
                ('product_description', models.TextField(verbose_name='Описание продукта')),
                ('product_price', models.IntegerField(verbose_name='Цена продукта')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Рассмотрение')),
                ('review_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.product')),
            ],
        ),
    ]
