# Generated by Django 3.2 on 2021-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_author',
            field=models.CharField(max_length=20, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
    ]
